# Generated by Django 3.2.5 on 2021-07-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='Contact',
        ),
    ]
